### ISSUE TITLE
Dispose() method is missing (files remain locked until PowerShell is closed

### ISSUE THREAD

**Issue by joesuffceren** [billgraziano/CsvDataReader#9]
The code and sample script mentions a dispose() method, but that method doesn't seem to be present in the published DLL. Without the dispose method (even if reader.close() is called), the CSV files remain locked until the PowerShell window is closed. 
![image](https://cloud.githubusercontent.com/assets/8726407/5710480/9790dbda-9a5f-11e4-825e-b1243d15edf4.png)

**Comment by billgraziano** [comment]
I also received this:


Hi!  I just wanted you to know that the CsvDataReader doesn't release the file handle so you can't move the file to an archive folder.  I would put in a pull request in github, but had to use a newer version of VS in my edit.

**Comment by joesuffceren** [comment]
hey, Bill! Happy to see some activity on this project! I love it and appreciate the work you've done with it. If you need any more info from me on this or the other reports I've logged, please let me know, and I'd be happy to provide info, test releases, etc.
